version: '3'
services:
  minecraft:
    image: openhack/minecraft-server:2.0
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: TRUE
    isolation: hyperv
    deploy:
      resources:
        limits:
          memory: 1536M
