# Turns out this doesn't work because Docker Compose v3 doesn't
# support 'isolation' and we only have a 2016-based image currently
version: '3'
services:
  minecraft:
    image: openhack/minecraft-server:2.0
    ports:
      - 25565:25565
      - 25575:25575
    environment:
      EULA: TRUE
    isolation: hyperv